void parse();
void next();
void parseerror();
void match(int what);

Pnode parse_program();
Pnode parse_stat_list();
Pnode parse_stat();
Pnode parse_def_stat();
Pnode parse_id_list();
Pnode parse_type();
Pnode parse_atomic_type();
Pnode parse_table_type();
Pnode parse_attr_list();
Pnode parse_attr_decl();
Pnode parse_assign_stat();
Pnode parse_expr();
Pnode parse_bool_term();
Pnode parse_comp_term();
Pnode parse_low_term();
Pnode parse_factor();
Pnode parse_unary_op();

Pnode parse_join_op();
Pnode parse_project_op();
Pnode parse_select_op();
Pnode parse_exists_op();
Pnode parse_all_op();
Pnode parse_extend_op();
Pnode parse_update_op();
Pnode parse_rename_op();
Pnode parse_const();
Pnode parse_atomic_const();
Pnode parse_table_const();
Pnode parse_tuple_const();
Pnode parse_if_stat();
Pnode parse_while_stat();
Pnode parse_read_stat();
Pnode parse_specifier();
Pnode parse_write_stat();

int errors;
